name: AutoCut CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[all]'

      - name: Run black to check code formatting
        run: |
          black . --check
        continue-on-error: true

      - name: Format code using black if needed
        if: failure()
        run: |
          black .
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto format code using black"
          git push origin main

      - name: Run tests
        run: |
          pytest

  docker:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: "latest"
          driver: docker-container

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/autocut:latest

  deploy:
    needs: docker
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull and run Docker container
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/autocut:latest
          docker run --rm -v ${{ secrets.VIDEO_DIRECTORY }}:/autocut/video ${{ secrets.DOCKERHUB_USERNAME }}/autocut:latest autocut -d /autocut/video
